version: "3"

services:

  rcon-web-admin:
    image: ghcr.io/emilgardis/rcon-web-admin
    build: .
    environment:
      RWA_USERNAME: ${RWA_USERNAME:?no username set}
      RWA_PASSWORD: ${RWA_PASSWORD:?no password set}
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: ${RWA_RCON_HOST:-}
      RWA_RCON_PASSWORD: ${RWA_PASSWORD:-}
    ports:
      - "4326:4326"
    volumes:
      - "db:/opt/rcon-web-admin/db"
volumes:
  db: