name: docker
on:
  push:
    branches: ['main']
    tags: ["v*"]
jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Set tag
        run: echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
      - name: Set rev
        run: echo "REV=${{ github.sha }}" >> $GITHUB_ENV
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v1.3.0
        with:
          push: true
          files: docker-bake.hcl